# Generated by Django 2.1.2 on 2019-01-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('buildingname', models.TextField()),
                ('own', models.TextField()),
                ('num1', models.TextField()),
                ('num2', models.TextField()),
                ('num3', models.TextField()),
                ('num4', models.TextField()),
                ('num5', models.TextField()),
                ('num6', models.TextField()),
                ('num7', models.TextField()),
                ('num8', models.TextField()),
                ('num9', models.TextField()),
                ('num10', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member')),
            ],
        ),
    ]
